import { readFileSync, writeFileSync } from "fs";

const FILE = "public/data.js";
const src = readFileSync(FILE, "utf8");

// Enrichissement par id : { year, publisher, country, descriptionFull }
// Pour les outils connus -> données vérifiables. Sinon -> valeurs par défaut + TODO.
const ENRICH = {
  claude: { year: "2023", publisher: "Anthropic", country: "USA", descriptionFull: "Modèle de langage d'Anthropic reconnu pour son écriture fluide, contextualisée et proche de l'humain. Très apprécié en rédaction professionnelle, en analyse de documents longs et en raisonnement. Points forts : grande qualité de rédaction et capacité de contexte étendue. Points faibles : accès à certaines fonctions réservé à l'offre payante." },
  chatgpt: { year: "2022", publisher: "OpenAI", country: "USA", descriptionFull: "Assistant polyvalent d'OpenAI, idéal pour le brainstorming rapide, la résolution de problèmes et l'assistance quotidienne. Large écosystème de plugins et d'outils. Points forts : univers d'usages très riche et base d'utilisateurs mondiale. Points faibles : dépendance au service et limites de facturation sur l'offre gratuite." },
  deepseek: { year: "2024", publisher: "DeepSeek", country: "Chine", descriptionFull: "Modèle de langage ultra-puissant et très économique, adapté aux prompts complexes et aux tâches exigeantes. Offre un excellent rapport performance/coût pour les utilisateurs avancés. Points forts : capacité de raisonnement et prix très compétitifs. Points faibles : données et services hébergés hors UE/USA à évaluer selon vos exigences." },
  qwen: { year: "2023", publisher: "Alibaba", country: "Chine", descriptionFull: "Famille de modèles multilingues d'Alibaba, performante en génération de code et en compréhension multilingue. Points forts : bonnes performances en code et prise en charge de nombreuses langues. Points faibles : documentation et notoriété moindres que les grands acteurs occidentaux." },
  gemini: { year: "2023", publisher: "Google", country: "USA", descriptionFull: "Famille de modèles multimodaux de Google, intégrée à l'écosystème Google (Search, YouTube, Workspace). Excellent pour la recherche avancée et le raisonnement multimodal. Points forts : intégration Google et gratuité de la version de base. Points faibles : fonctionnalités avancées réservées aux abonnés." },
  copilot: { year: "2023", publisher: "Microsoft", country: "USA", descriptionFull: "Assistant IA de Microsoft intégré à l'écosystème Microsoft 365, Windows et Edge. Facilite la rédaction, l'analyse et la productivité au quotidien. Points forts : intégration native avec les outils Microsoft. Points faibles : nécessite un compte Microsoft et certaines fonctions sont payantes." },
  mistral: { year: "2023", publisher: "Mistral AI", country: "France", descriptionFull: "Champion européen de l'IA, Mistral propose des modèles open-source et l'assistant 'Le Chat'. Alternative souveraine et européenne, appréciée pour son ouverture. Points forts : open-source, souveraineté européenne et 'Le Chat' gratuit. Points faibles : écosystème moins fourni que les leaders américains." },
  huggingface: { year: "2016", publisher: "Hugging Face", country: "USA", descriptionFull: "Plateforme de référence pour les modèles open-source, les datasets et les espaces de démonstration. Incontournable de la communauté IA. Points forts : vaste bibliothèque de modèles et d'outils. Points faibles : courbe d'apprentissage pour les débutants." },
  kimi: { year: "2023", publisher: "Moonshot AI", country: "Chine", descriptionFull: "Assistant doté d'une très grande fenêtre de contexte, adapté à l'analyse de longs documents. Points forts : capacité à traiter de très longs textes. Points faibles : notoriété et disponibilité moindres hors de la Chine." },
  perplexity: { year: "2022", publisher: "Perplexity AI", country: "USA", descriptionFull: "Moteur de réponse avec citations et sources, parfait pour la recherche rapide et vérifiée. Points forts : réponses sourcées avec liens. Points faibles : offres avancées payantes et rationalisation des citations selon les requêtes." },
  ithy: { year: "2023", publisher: "Inconnu", country: "USA", descriptionFull: "Outil de recherche produisant des rapports complets et structurés. Points forts : synthèses organisées. Points faibles : offre payante et notoriété limitée. // TODO: vérifier éditeur et année de parution." },
  notebooklm: { year: "2023", publisher: "Google", country: "USA", descriptionFull: "Outil de Google pour analyser et synthétiser vos PDFs et documents. Très utile pour prendre des notes et générer des synthèses à partir de sources. Points forts : analyse de documents et gratuité. Points faibles : limité au format texte/document." },
  googletrends: { year: "2006", publisher: "Google", country: "USA", descriptionFull: "Outil gratuit de Google pour suivre les tendances de recherche et les mots-clés. Utile pour l'analyse de marché et la recherche de niches. Points forts : données réelles et gratuites. Points faibles : représentation relative et non absolue des volumes." },
  grok: { year: "2023", publisher: "xAI", country: "USA", descriptionFull: "Assistant IA de xAI, intégré à X (Twitter), qui exploite les tendances en temps réel. Points forts : accès aux données temps réel de X. Points faibles : réservé aux abonnés Premium de X." },
  openclaw: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Agent autonome sans code annoncé pour l'automatisation. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays, année et description détaillée." },
  maxclaw: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Agent avancé pour des automatisations complexes. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays, année et description détaillée." },
  n8n: { year: "2019", publisher: "n8n GmbH", country: "Allemagne", descriptionFull: "Plateforme d'automatisation de workflows avec flexibilité technique, très appréciée des développeurs. Permet de connecter de nombreux services et exécuter du code personnalisé. Points forts : auto-hébergement possible et open-source. Points faibles : courbe d'apprentissage pour les non-techniques." },
  make: { year: "2020", publisher: "Celonis", country: "République tchèque", descriptionFull: "Outil d'automatisation visuelle et simple, alternative à n8n et Zapier. Interface en glisser-déposer pour créer des scénarios. Points forts : simplicité d'utilisation et scénarios visuels. Points faibles : opérations avancées limitées sur l'offre gratuite." },
  coze: { year: "2023", publisher: "ByteDance", country: "Chine", descriptionFull: "Plateforme pour créer des bots conversationnels pour TikTok, WhatsApp et d'autres canaux. Points forts : création de bots sans code et intégration sociale. Points faibles : dépendance à l'écosystème ByteDance." },
  zapier: { year: "2011", publisher: "Zapier", country: "USA", descriptionFull: "Plateforme populaire d'automatisation de workflows reliant des milliers d'applications. Points forts : catalogue d'intégrations très large. Points faibles : coût qui monte vite et limites de l'offre gratuite." },
  lindy: { year: "2023", publisher: "Lindy AI", country: "USA", descriptionFull: "Plateforme d'agents IA spécialisée dans la délégation de tâches métier. Points forts : agents autonomes dédiés à des tâches précises. Points faibles : offre payante." },
  lovable: { year: "2023", publisher: "Lovable", country: "Suède", descriptionFull: "Outil permettant de créer des applications web fonctionnelles sans coder, piloté par l'IA. Points forts : génération rapide d'apps complètes. Points faibles : offre payante pour les usages avancés." },
  nanobanana: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil de génération d'images ultra-réaliste avec précision anatomique. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  lovart: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil de design produit et de visuels commerciaux. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  canva: { year: "2013", publisher: "Canva", country: "Australie", descriptionFull: "Outil de design en ligne tout-en-un, idéal pour créer des posts réseau social et des supports visuels rapidement. Points forts : accessibilité pour les non-designers et bibliothèque de templates. Points faibles : fonctions avancées et IA réservées à l'offre payante." },
  firefly: { year: "2023", publisher: "Adobe", country: "USA", descriptionFull: "Suite de génération d'images d'Adobe conçue pour du contenu sans problème de droits. S'intègre à Photoshop et à l'écosystème Adobe. Points forts : contenu 'sans copyright' et intégration Adobe. Points faibles : nécessite un abonnement Adobe pour un usage étendu." },
  dreamina: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil de génération d'images annoncé gratuit et illimité. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  midjourney: { year: "2022", publisher: "Midjourney Inc.", country: "USA", descriptionFull: "Générateur d'images au style artistique reconnu, prisé des créatifs. Points forts : qualité esthétique et style unique. Points faibles : accessible principalement via Discord et offre entièrement payante." },
  stablediffusion: { year: "2022", publisher: "Stability AI", country: "UK (Royaume-Uni)", descriptionFull: "Modèle open-source de génération d'images, très flexible et auto-hébergeable. Points forts : open-source, personnalisation et contrôle local. Points faibles : nécessite du matériel ou une plateforme pour un usage optimal." },
  runway: { year: "2018", publisher: "Runway AI", country: "USA", descriptionFull: "Plateforme de création et d'édition vidéo assistée par IA. Points forts : outils vidéo génératifs avancés. Points faibles : offre payante et consommation de crédits." },
  wanvideo: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé de génération de vidéo à partir de texte. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  seedance: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé de génération vidéo avec mouvement fluide et réaliste. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  kling: { year: "2024", publisher: "Kling AI (Kuaishou)", country: "Chine", descriptionFull: "Générateur de vidéo IA réputé pour son réalisme extrême. Points forts : qualité vidéo très réaliste. Points faibles : offre payante." },
  hailuo: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé pour créer de courts métrages et clips. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  grokimage: { year: "Inconnue", publisher: "xAI", country: "USA", descriptionFull: "Fonctionnalité annoncée de transformation d'image en vidéo chez xAI. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  sora: { year: "2024", publisher: "OpenAI", country: "USA", descriptionFull: "Générateur de vidéo d'OpenAI, capable de produire des séquences réalistes à partir de texte. Points forts : réalisme et contrôle. Points faibles : accès limité et offre payante." },
  capcut: { year: "2019", publisher: "ByteDance", country: "Chine", descriptionFull: "Application de montage vidéo, très utilisée pour créer des Reels et des vidéos TikTok facilement. Points forts : gratuit, nombreux templates et effets. Points faibles : fonctions avancées payantes." },
  davinci: { year: "2004", publisher: "Blackmagic Design", country: "Australie", descriptionFull: "Suite de montage et d'étalonnage professionnelle avec version gratuite très complète. Points forts : version gratuite pro et outils d'étalonnage. Points faibles : courbe d'apprentissage et configuration avancée." },
  obs: { year: "2012", publisher: "OBS Project", country: "USA", descriptionFull: "Logiciel open-source de capture d'écran et de streaming, standard de la diffusion en direct. Points forts : gratuit, open-source et puissant. Points faibles : configuration technique." },
  canvavid: { year: "2019", publisher: "Canva", country: "Australie", descriptionFull: "Montage vidéo express en ligne intégré à Canva, idéal pour du contenu rapide. Points forts : simplicité et intégration Canva. Points faibles : moins de contrôle qu'un logiciel de montage dédié." },
  openshot: { year: "2008", publisher: "OpenShot Studios", country: "USA", descriptionFull: "Logiciel de montage vidéo open-source, simple et léger. Points forts : gratuit et accessible. Points faibles : fonctionnalités plus limitées sur des projets complexes." },
  descript: { year: "2017", publisher: "Descript", country: "USA", descriptionFull: "Outil de montage vidéo/audio piloté par transcription : vous éditez le texte, la vidéo suit. Points forts : approche par transcription très efficace. Points faibles : offre payante." },
  voicebox: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé de clonage de voix. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  elevenlabs: { year: "2022", publisher: "ElevenLabs", country: "UK (Royaume-Uni)", descriptionFull: "Plateforme de synthèse vocale à la voix humaine très réaliste, multi-langues. Points forts : qualité vocale proche de l'humain. Points faibles : offre payante pour un usage étendu." },
  adobepodcast: { year: "2021", publisher: "Adobe", country: "USA", descriptionFull: "Outil d'Adobe qui nettoie l'audio automatiquement (bruit, réverbération) pour les podcasts. Points forts : amélioration audio en un clic et gratuit. Points faibles : limité au traitement d'enrichissement audio." },
  murf: { year: "2020", publisher: "Murf AI", country: "Singapour", descriptionFull: "Outil de voix-off professionnelle avec de nombreuses voix et langues. Points forts : qualité studio et variété de voix. Points faibles : offre payante." },
  naturalreader: { year: "2014", publisher: "Natural Reader", country: "USA", descriptionFull: "Outil de synthèse vocale (texte vers voix) pour lire documents et textes à voix haute. Points forts : accessibilité et nombreuses voix. Points faibles : offres avancées payantes." },
  aiva: { year: "2016", publisher: "AIVA Technologies", country: "Luxembourg", descriptionFull: "Outil de composition musicale par IA, pour créer des musiques originales. Points forts : composition originale. Points faibles : offre payante pour générer et télécharger sans droits." },
  suno: { year: "2023", publisher: "Suno", country: "USA", descriptionFull: "Outil capable de générer une chanson complète (paroles, musique, voix) à partir d'un prompt. Points forts : chansons complètes et de qualité. Points faibles : offre payante pour un usage et des droits étendus." },
  lyria: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé pour générer des instrumentaux professionnels. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  mureka: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé de génération musicale sans problème de droits. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  udio: { year: "2024", publisher: "Udio", country: "USA", descriptionFull: "Générateur de musique IA à la qualité studio, depuis un simple prompt. Points forts : qualité de production. Points faibles : offre payante." },
  soundraw: { year: "2019", publisher: "Soundraw", country: "Japon", descriptionFull: "Outil de génération de musique libre de droits, souvent utilisé pour YouTube. Points forts : musique générée adaptée aux vidéos. Points faibles : offre payante." },
  heygen: { year: "2020", publisher: "HeyGen", country: "USA", descriptionFull: "Outil de création d'avatars multilingues pour vidéos. Points forts : avatars réalistes et traduction automatique. Points faibles : offre payante." },
  pippit: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé d'avatar vendeur. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  did: { year: "2019", publisher: "D-ID", country: "Israël", descriptionFull: "Outil qui anime une photo pour la faire parler, idéal pour des vidéos à partir d'images. Points forts : 'photo qui parle' facile. Points faibles : offre payante." },
  synthesia: { year: "2017", publisher: "Synthesia", country: "UK (Royaume-Uni)", descriptionFull: "Plateforme d'avatars IA pour créer des vidéos de formation et d'entreprise. Points forts : avatars professionnels et multi-langues. Points faibles : offre entièrement payante." },
  zimage: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé pour créer des photos de profil IA. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  canvadesign: { year: "2013", publisher: "Canva", country: "Australie", descriptionFull: "Version 'design' tout-en-un de Canva pour créer supports et visuels. Points forts : polyvalence et simplicité. Points faibles : fonctions avancées payantes." },
  designer: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé de design rapide. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  figma: { year: "2012", publisher: "Figma", country: "USA", descriptionFull: "Outil de design UI/UX professionnel, collaboratif et multi-utilisateurs. Points forts : collaboration temps réel et prototypes. Points faibles : offre payante pour les équipes et fonctions avancées." },
  gimp: { year: "1998", publisher: "GIMP Team", country: "USA", descriptionFull: "Logiciel libre de retouche d'image, alternative gratuite à Photoshop. Points forts : gratuit, open-source et complet. Points faibles : interface moins moderne et courbe d'apprentissage." },
  freepik: { year: "2010", publisher: "Freepik", country: "Espagne", descriptionFull: "Banque de templates et d'images enrichie de fonctions IA générative. Points forts : ressources nombreuses + IA. Points faibles : accès aux ressources premium payant." },
  notion: { year: "2013", publisher: "Notion Labs", country: "USA", descriptionFull: "Outil tout-en-un de productivité, souvent décrit comme un 'second cerveau' : notes, bases de données, wiki et projets. Points forts : flexibilité et organisation. Points faibles : courbe d'apprentissage et fonctions avancées payantes." },
  antigravity: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Outil annoncé d'écriture collaborative avec Google Drive. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  languagetool: { year: "2005", publisher: "LanguageTooler GmbH", country: "Allemagne", descriptionFull: "Correcteur grammatical et stylistique avancé, multi-langues. Points forts : correction de qualité et gratuité de base. Points faibles : versions étendues payantes." },
  copyai: { year: "2020", publisher: "Copy.ai", country: "USA", descriptionFull: "Outil de génération de textes de vente et de persuasion pour le marketing. Points forts : copywriting rapide. Points faibles : offre payante." },
  gamma: { year: "2020", publisher: "Gamma", country: "USA", descriptionFull: "Outil de création de présentations automatiques par IA. Points forts : génération de slides rapide. Points faibles : offre payante." },
  substack: { year: "2017", publisher: "Substack", country: "USA", descriptionFull: "Plateforme de newsletters avec monétisation par abonnement payant. Points forts : diffusion d'audience et monétisation. Points faibles : commission sur les abonnements payants." },
  buffer: { year: "2010", publisher: "Buffer", country: "USA", descriptionFull: "Outil de programmation de publications sur les réseaux sociaux. Points forts : planification multi-réseaux. Points faibles : offre payante pour plusieurs comptes." },
  brevo: { year: "2012", publisher: "Brevo (ex Sendinblue)", country: "France", descriptionFull: "Outil d'email marketing (ex Sendinblue) pour campagnes et automatisations. Points forts : offre freemium et écosystème complet. Points faibles : limites de volume sur l'offre gratuite." },
  mailerlite: { year: "2010", publisher: "MailerLite", country: "Lituanie", descriptionFull: "Outil d'email marketing gratuit et simple, adapté aux petits créateurs. Points forts : gratuité généreuse et simplicité. Points faibles : fonctionnalités avancées payantes." },
  systemeio: { year: "2019", publisher: "Systeme.io", country: "France", descriptionFull: "Plateforme tout-en-un pour funnels de vente et email marketing en français. Points forts : complet et accessible. Points faibles : offre payante." },
  gumroad: { year: "2011", publisher: "Gumroad", country: "USA", descriptionFull: "Plateforme de vente de produits numériques (ebooks, formations, logiciels). Points forts : simple à vendre et à installer. Points faibles : commission sur les ventes." },
  stripe: { year: "2010", publisher: "Stripe", country: "USA", descriptionFull: "Solution de paiement en ligne professionnelle, très utilisée par les développeurs. Points forts : API robuste et paiements internationaux. Points faibles : frais par transaction." },
  kofi: { year: "2017", publisher: "Ko-fi", country: "UK (Royaume-Uni)", descriptionFull: "Plateforme pour recevoir des dons et créer une boutique, alternative conviviale. Points forts : dons et boutique simples, faible commission. Points faibles : fonctionnalités complètes payantes." },
  woocommerce: { year: "2011", publisher: "WooCommerce (Automattic)", country: "USA", descriptionFull: "Extension open-source de boutique en ligne pour WordPress. Points forts : gratuit et personnalisable. Points faibles : hébergement et extensions payants." },
  paypal: { year: "1998", publisher: "PayPal", country: "USA", descriptionFull: "Solution de paiement rapide et largement utilisée dans le monde. Points forts : confiance et couverture mondiale. Points faibles : frais par transaction." },
  aistudio: { year: "2023", publisher: "Google", country: "USA", descriptionFull: "Studio de Google pour tester Gemini et d'autres modèles en ligne. Points forts : accès gratuit aux modèles Google. Points faibles : pensé pour les tests plutôt que l'usage métier." },
  github: { year: "2008", publisher: "Microsoft", country: "USA", descriptionFull: "Plateforme de développement pour héberger le code et constituer un portfolio. Points forts : standard de l'industrie et gratuit. Points faibles : libre accès des dépôts publics aux référentiels par défaut." },
  cloudflare: { year: "2009", publisher: "Cloudflare", country: "USA", descriptionFull: "Réseau de CDN et d'hébergement avec offre gratuite, pour performance et sécurité. Points forts : gratuit, CDN mondial, protection DDoS. Points faibles : certaines fonctions avancées payantes." },
  openrouter: { year: "2023", publisher: "OpenRouter", country: "USA", descriptionFull: "API unique pour accéder à de nombreux modèles d'IA sans multiplier les abonnements. Points forts : accès unifié aux modèles. Points faibles : paiement à l'usage." },
  cursor: { year: "2023", publisher: "Anysphere (Cursor)", country: "USA", descriptionFull: "Éditeur de code boosté par l'IA pour coder plus vite. Points forts : autocomplétion et assistance contextuelles. Points faibles : offre payante." },
  githubcopilot: { year: "2021", publisher: "GitHub / Microsoft", country: "USA", descriptionFull: "Assistant de code intégré à l'éditeur, propulsé par l'IA. Points forts : complétion pertinente. Points faibles : abonnement payant." },
  windsurf: { year: "2023", publisher: "Windsurf (ex Codeium)", country: "USA", descriptionFull: "IDE (environnement de développement) propulsé par l'IA. Points forts : assistance complète au code. Points faibles : offre payante." },
  tabnine: { year: "2013", publisher: "Tabnine", country: "Israël", descriptionFull: "Complétion de code sécurisée, pensé pour la confidentialité des entreprises. Points forts : sécurité et conformité. Points faibles : offre payante." },
  sifuyik: { year: "Inconnue", publisher: "Inconnu", country: "Inconnu", descriptionFull: "Créateur de tutoriels IA courts et pratiques. Fiche à compléter et lien à vérifier. // TODO: vérifier éditeur, pays et année." },
  googleai: { year: "2023", publisher: "Google", country: "USA", descriptionFull: "Certification gratuite en IA proposée par Google Cloud. Points forts : certification reconnue et gratuite. Points faibles : niveau technique requis." },
  openaiacademy: { year: "2024", publisher: "OpenAI", country: "USA", descriptionFull: "Plateforme de cours officiels proposée par OpenAI. Points forts : contenu officiel et fiable. Points faibles : catalogue encore limité." },
  "youtube-tuto": { year: "2005", publisher: "Google (YouTube)", country: "USA", descriptionFull: "Accès à un apprentissage gratuit et varié via des tutoriels vidéo. Points forts : gratuit et vaste choix. Points faibles : qualité variable selon les sources." },
  freecodecamp: { year: "2014", publisher: "freeCodeCamp", country: "USA", descriptionFull: "Plateforme gratuite de cours en développement et IA, avec certification. Points forts : 100% gratuit et certification. Points faibles : format long à compléter." },
  youtube: { year: "2005", publisher: "Google (YouTube)", country: "USA", descriptionFull: "Plateforme vidéo à fort potentiel SEO à long terme. Points forts : gratuit et référencement durable. Points faibles : concurrence forte et temps nécessaire." },
  facebook: { year: "2004", publisher: "Meta", country: "USA", descriptionFull: "Réseau social utile pour bâtir une communauté et des groupes. Points forts : portée et groupes. Points faibles : portée organique en baisse." },
  tiktok: { year: "2016", publisher: "ByteDance", country: "Chine", descriptionFull: "Réseau social vidéo court à fort potentiel de viralité rapide. Points forts : viralité et audience jeune. Points faibles : algorithme imprévisible." },
  instagram: { year: "2010", publisher: "Meta", country: "USA", descriptionFull: "Réseau social visuel orienté image de marque et esthétique. Points forts : engagement visuel fort. Points faibles : nécessité de production de contenu visuel." },
  discord: { year: "2015", publisher: "Discord", country: "USA", descriptionFull: "Plateforme communautaire pour fédérer et engager une audience. Points forts : communauté et interaction. Points faibles : gestion et animation nécessaires." }
};

const out = src.split("\r\n").map((line) => {
  const m = line.match(/^(\s*\{ id: "([^"]+)".*?)(\},?)$/);
  if (!m) return line;
  const [, prefix, id, tail] = m;
  const e = ENRICH[id];
  if (!e) {
    throw new Error("Aucune entrée pour id=" + id);
  }
  const fields =
    `,\n    year: "${e.year}",\n    publisher: "${e.publisher}",\n    country: "${e.country}",\n    descriptionFull: "${e.descriptionFull}"\n  `;
  return prefix + fields + tail;
});

writeFileSync(FILE, out.join("\r\n"), "utf8");
console.log("Enrichissement terminé. " + Object.keys(ENRICH).length + " entrées couvertes.");
